version: '3.5'

services:
  prospero:
    container_name: prospero-service
    init: true
    image: ghcr.io/prospero-inc/prospero-backend:latest
    environment:
      NODE_ENV: production
      API_BASE_URL: ${API_BASE_URL}
      API_BASE_URL_RESET: ${API_BASE_URL_RESET}
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      SECRET: ${SECRET}
      GMAIL_OAUTH_CLIENT_ID: ${GMAIL_OAUTH_CLIENT_ID}
      GMAIL_OAUTH_CLIENT_SECRET: ${GMAIL_OAUTH_CLIENT_SECRET}
      GMAIL_OAUTH_REDIRECT_URI: ${GMAIL_OAUTH_REDIRECT_URI}
      GMAIL_TOKEN_ENCRYPTION_KEY: ${GMAIL_TOKEN_ENCRYPTION_KEY}
      GMAIL_OAUTH_SUCCESS_REDIRECT_URL: ${GMAIL_OAUTH_SUCCESS_REDIRECT_URL}
    ports:
      - '3000:3000'
    networks:
      - prospero

networks:
  prospero:
    external: true
