version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://postgres:1234567@prospero-db:5432/prospero
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - my-network

networks:
  my-network:
    external: true
