version: '3.5'

services:
  prospero:
    container_name: prospero-service
    init: true
    image: prospero-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        API_BASE_URL: ${API_BASE_URL}
        API_BASE_URL_RESET: ${API_BASE_URL_RESET}
        DATABASE_URL: ${DATABASE_URL}
        DIRECT_URL: ${DIRECT_URL}
        DOPPLER_CONFIG: ${DOPPLER_CONFIG}
        DOPPLER_ENVIRONMENT: ${DOPPLER_ENVIRONMENT}
        DOPPLER_PROJECT: ${DOPPLER_PROJECT}
        MAIL_FROM: ${MAIL_FROM}
        MAIL_HOST: ${MAIL_HOST}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_SERVICE: ${MAIL_SERVICE}
        MAIL_USER: ${MAIL_USER}
        SECRET: ${SECRET}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - prospero

networks:
  prospero:
    external: true
