name: Node.js CI

on:
  push:
    branches: ['developer']
  pull_request:
    branches: ['developer']

jobs:
  create-docker-image:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_DEPLOY}}

      - name: Build image
        run: |
          docker build . -tag ghcr.io/natividev/prospero-backend:latest
          docker push ghcr.io/natividev/prospero-backend:latest

  deploy:
    needs: create-docker-image
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'npm'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_DEPLOY}}

      - name: Deploy to Docker
        run: |
          docker pull ghcr.io/natividev/prospero-backend:latest
          docker stop prospero-backend && docker rm prospero-backend
          docker run -d -p 3000:3000 ghcr.io/natividev/prospero-backend:latest
