name: Node.js CI

on:
  push:
    branches:
      - developer

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: Stop existing container
        run: |
          docker compose --env-file ~/secrets/prospero-backend.env down --rmi all

      - name: Deploy Docker container
        run: |
          docker compose --env-file ~/secrets/prospero-backend.env up --build -d
