name: Node.js CI

on:
  push:
    branches: ['developer']
  pull_request:
    branches: ['developer']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Doppler CLI
        run: |
          curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo apt-key add -
          echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
          sudo apt-get update && sudo apt-get -y install doppler

      - name: Authenticate with Doppler
        run: |
          echo ${{ secrets.DOPPLER_TOKEN_API }} | doppler login --token

      - name: Build Docker image
        run: |
          doppler run -- docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t prospero-app .
