name: Node.js CI

on:
  push:
    branches: ['developer']
  pull_request:
    branches: ['developer']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build Docker image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t prospero-app .

      - name: Run Docker container
        run: |
          docker run -d --name prospero-app-container -e DATABASE_URL=${{ secrets.DATABASE_URL }} prospero-app

      - name: Check Docker container status
        run: |
          docker ps -a