name: Node.js CI

on:
  push:
    branches: ['developer']
  pull_request:
    branches: ['developer']

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t prospero-backend:latest .

      - name: Stop existing container
        run: |
          docker stop prospero-backend || true
          docker rm prospero-backend || true

      - name: Deploy Docker container
        run: |
          docker run -d -p 3000:3000 --name prospero-backend \
          -e DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN_API }} \
          prospero-backend:latest \
          doppler run -- npm run start:prod
