name: Node.js CI

on:
  push:
    branches:
      - developer

jobs:
  deploy:
    runs-on: self-hosted

    env:
      NODE_ENV: production
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_BASE_URL_RESET: ${{ secrets.API_BASE_URL_RESET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
      DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
      DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_SERVICE: ${{ secrets.MAIL_SERVICE }}
      MAIL_USER: ${{ secrets.MAIL_USER }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: List Docker containers before stopping
        run: docker ps -a

      - name: List Docker images before stopping
        run: docker images

      - name: Stop existing container
        run: |
          docker compose down --rmi all --volumes --remove-orphans
          docker image prune -af
        continue-on-error: true

      - name: List Docker containers after stopping
        run: docker ps -a

      - name: List Docker images after stopping
        run: docker images

      - name: Deploy Docker container
        run: |
          docker compose up -d --build

      - name: List Docker containers after deployment
        run: docker ps -a

      - name: List Docker images after deployment
        run: docker images
